sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t lkhlkh/sample-app -f Dockerfile .
script:
    - docker run --rm -p 80:80 --name react-app lkhlkh/sample-app

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "Sample-React"
  env: "Samplereact-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-681883041094"
  bucket_path: "EBApptest"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"